# Sample config.yaml

pipeline: both  # Options: metadata, columns, both

paths:
  dataset_for_test: "./data/datasets/opsi-test"
  dataset_for_train: "./data/datasets/opsi-train"
  faiss_index_metadata_path: "./data/models/faiss-index-general.index"
  faiss_index_column_path: "./data/models/faiss-index-columns.index"
  id_metadata_tracker_json: "./data/models/id_tracker.json"
  id_column_tracker_json: "./data/models/id_tracker_columns.json"
  metadata_dir: "./data/models/metadata_generated"
  columns_dir: "./data/models/column_metadata"
  reports_dir: "./data/reports"
  ontology_terms_json: "./data/ontology/ontology_terms.json"
  faiss_index_ontology_path: "./data/models/ontology_index.faiss"
  id_ontology_tracker_json: "./data/models/ontology_id_tracker.json"
  # OAEI
  mouse_ontology: "./data/datasets/anatomy-dataset/mouse.owl"
  human_ontology: "./data/datasets/anatomy-dataset/human.owl"
  mouse_human_alignment: "./data/datasets/anatomy-dataset/reference.rdf"
  human_index: "./data/models/anatomy-dataset/human_index.faiss"
  mouse_index: "./data/models/anatomy-dataset/mouse_index.faiss"
  human_id_tracker: "./data/models/anatomy-dataset/human_id_tracker.faiss"
  mouse_id_tracker: "./data/models/anatomy-dataset/mouse_id_tracker.faiss"
  human_terms_json: "./data/ontology/human_terms_enriched.json"
  mouse_terms_json: "./data/ontology/mouse_terms_enriched.json"
  mouse_testset: "./data/datasets/anatomy-dataset/mouse_testset.json"

namespaces:
  mouse: "http://mouse.owl#"
  human: "http://human.owl#"

models:
  embedding_model: "intfloat/multilingual-e5-large"
  generation_model: "google/gemma-2b-it"

remote:
  use_remote: false
  rclone_remote_name: "onedrive"
  remote_data_dir: "my_rag_project_data"

logging:
  level: INFO
  log_file: null  # Optionally set to a file path if you want to log to file

k_neighbours: 3
batch_size: 16

# download
data_load:
  target_count: 100
  opsi_api_list: "https://podatki.gov.si/api/3/action/package_list"
  opsi_api_show: "https://podatki.gov.si/api/3/action/package_show?id="
  error_log: "./data/error_log.txt"
