# Sample config.yaml

pipeline: both  # Options: metadata, columns, both

paths:
  dataset_for_test: "./data/datasets/opsi-test"
  dataset_for_train: "./data/datasets/opsi-train"
  faiss_index_metadata_path: "./data/models/faiss-index-general.index"
  faiss_index_column_path: "./data/models/faiss-index-columns.index"
  id_metadata_tracker_json: "./data/models/id_tracker.json"
  id_column_tracker_json: "./data/models/id_tracker_columns.json"
  metadata_dir: "./data/models/metadata_generated"
  columns_dir: "./data/models/column_metadata"
  reports_dir: "./data/reports"

models:
  embedding_model: "intfloat/multilingual-e5-large"
  generation_model: "google/gemma-2b-it"

remote:
  use_remote: false
  rclone_remote_name: "onedrive"
  remote_data_dir: "my_rag_project_data"

logging:
  level: INFO
  log_file: null  # Optionally set to a file path if you want to log to file

k_neighbours: 3
batch_size: 16

# download
data_load:
  target_count: 100
  opsi_api_list: "https://podatki.gov.si/api/3/action/package_list"
  opsi_api_show: "https://podatki.gov.si/api/3/action/package_show?id="
  error_log: "./data/error_log.txt"
